WIP

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -24,8 +24,15 @@ jobs:
           base_branch="${{ github.base_ref }}"
           merging_branch="${{ github.head_ref }}"
 
+          set +e
           git merge-base --is-ancestor "origin/$base_branch" "origin/$merging_branch"
+          status=$?
+          set -e
+
           if [[ $? -eq 1 ]]; then
             echo "::error::Branch ${merging_branch} is not up to date with ${base_branch}"
             exit 1
+          elif [[ $? -ne 0 ]]; then
+            echo "::error::Unable to determine if ${merging_branch} is up to date with ${base_branch}"
+            exit 2
           fi
